### ISSUE TITLE
python_cpp is failing on OS X

### ISSUE THREAD

**Issue by thomasvl** [google/protobuf#1253]
Travis is showing this, but my assumption is this build likely fails on any OS X machine running 10.11.

travis.sh sets DYLD_LIBRARY_PATH with a relative path, that likely could trip up the new security checks on 10.11.  That could be fixable with a patch like:

```
diff --git a/travis.sh b/travis.sh
index c973ec6..9f81e26 100755
--- a/travis.sh
+++ b/travis.sh
@@ -242,7 +242,8 @@ build_python_cpp() {
   internal_build_cpp
   internal_install_python_deps
   export LD_LIBRARY_PATH=../src/.libs # for Linux
-  export DYLD_LIBRARY_PATH=../src/.libs # for OS X
+  # Use absolute paths for keep OS X's security happy.
+  export DYLD_LIBRARY_PATH="`pwd`/src/.libs" # for OS X
   cd python
   # Only test Python 2.6/3.x on Linux
   if [ $(uname -s) == "Linux" ]; then
```

But even then the build fails.  Scanning the log I'm also seeing:

```
ld: warning: ignoring file ../src/.libs/libprotobuf.dylib, file was built for x86_64 which is not the architecture being linked (i386): ../src/.libs/libprotobuf.dylib
```

I don't know enough about the python build side of things to say why something is trying to build 32bit instead of 64bit.

**Comment by pgrosu** [comment]
I believe that `python_cpp` actually builds on a Linux machine, since I see `Description:	Ubuntu 12.04.5 LTS` and `Description:	Ubuntu 12.04.5 LTS` in the log file below:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/109330095/log.txt

In fact, just as a curiosity - as my local Mac is 10.11.3 - I ran the following commands:

```Bash
$ git clone --depth=50 https://github.com/google/protobuf.git google/protobuf
$ cd google/protobuf
$ git fetch origin +refs/pull/1240/merge:
$ git checkout -qf FETCH_HEAD
$ export CONFIG=python_cpp
$ export CXX=g++
$ export CC=gcc
$ g++ --version
$ ./travis.sh $CONFIG
```
Below is download link to the full output:

[python_cpp_mac-10_11_3.txt](https://www.dropbox.com/s/rk6rdie68w65mpk/python_cpp_mac-10_11_3.txt?dl=1)

It hits errors like this since it is looking for Linux shared libraries (`.so`) instead of `.dylib`:

```
[libprotobuf INFO conformance_test_runner.cc:121] child killed by signal 16
Traceback (most recent call last):
  File "./conformance_python.py", line 42, in <module>
    from google.protobuf import json_format
  File "/Users/paul/Desktop/protobuf/google/protobuf/python/google/protobuf/json_format.py", line 51, in <module>
    from google.protobuf import descriptor
  File "/Users/paul/Desktop/protobuf/google/protobuf/python/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/Users/paul/Desktop/protobuf/google/protobuf/python/google/protobuf/pyext/_message.so, 2): Library not loaded: /usr/local/lib/libprotobuf.10.dylib
  Referenced from: /Users/paul/Desktop/protobuf/google/protobuf/python/google/protobuf/pyext/_message.so
  Reason: image not found
```

~p

**Comment by thomasvl** [comment]
There are two entries on travis for it.  The second (failing one) is on OS X.  .so works just fine as a shared lib extension on OS X.

**Comment by thomasvl** [comment]
If you look back through the travis history, you'll see the test passing until I changed things to Xcode 7.2 which meant a new base OS X version for that travis image.

**Comment by thomasvl** [comment]
https://github.com/google/protobuf/pull/1255 used to mark it as failing so it won't fail other PRs/commits.

**Comment by pgrosu** [comment]
I'm learning new things every day :)  By the way, I noticed you put pwd, but I don't see any backticks like this:

```Bash
export DYLD_LIBRARY_PATH="`pwd`/src/.libs"
```

**Comment by thomasvl** [comment]
They were in there, but being seen as markdown.  Just tweaked the comment to make the whole thing a code block.

**Comment by pgrosu** [comment]
Ah, thanks - sorry.

**Comment by thomasvl** [comment]
np.  I keep forgetting to use mark down in the comments on issues.  :(

**Comment by pgrosu** [comment]
Ok, so I ran travis as sudo, but now the errors are a change in precision:

```
error: implicit conversion loses integer precision: 
``` 

Below is a link to the full log:

[sudo_travis_python_cpp.txt](https://www.dropbox.com/s/30nguo6k1764oft/sudo_travis_python_cpp.txt?dl=1)

**Comment by haberman** [comment]
It looks like Apple's new toolchain might have enabled the `-Wshorten-64-to-32` warning. We need to disable it since the protobuf codebase does rely on implicit shortening currently.

**Comment by haberman** [comment]
I believe this has been fixed.

**Comment by thomasvl** [comment]
@haberman: Do you want to remove the `allow_failures` entry?  https://github.com/google/protobuf/blob/master/.travis.yml#L70-L73

**Comment by thomasvl** [comment]
fyi - the build is actually still failing (https://travis-ci.org/google/protobuf/jobs/150645770), but it seems to be for a new reason compared to before.
