### ISSUE TITLE
3.0.2 is not available in package managers (npm, pypi, etc)

### ISSUE THREAD

**Issue by drobertduke** [google/protobuf#2115]
3.0.2 includes a critical [fix for node](https://github.com/google/protobuf/pull/1884) but it's not published.

**Comment by haberman** [comment]
I've published 3.0.2 packages for Node and Ruby.

**Comment by k0nserv** [comment]
It's still not published on Pypi. Any chances of this happening?

**Comment by xfxyjwf** [comment]
v3.2.0 has been out for a while. Please upgrade to the new version.
