### ISSUE TITLE
Add a BUILD rule for building the JavaLite proto runtime (similar to "protobuf_java")

### ISSUE THREAD

**Issue by cgrushko** [google/protobuf#2762]
(this is required for using Bazel's `java_lite_proto_library`)

@xfxyjwf

**Comment by cgrushko** [comment]
@xfxyjwf more and more people are asking about JavaLite support; do you have an estimate for when protobuf team is going to work on this, if at all?

**Comment by thaidn** [comment]
I really need JavaLite support because our open source project needs to run on Android.

**Comment by blerest** [comment]
Do you have any news regarding javalite support?

**Comment by xfxyjwf** [comment]
@cgrushko If we add a java_library rule for lite runtime in javalite branch, is it sufficient for java_lite_proto_library to work?

**Comment by xfxyjwf** [comment]
java_lite_proto_library should be working after https://github.com/google/protobuf/pull/3288

I have put up a working example here:
https://github.com/xfxyjwf/bazel_proto_examples

**Comment by xfxyjwf** [comment]
Fixed in https://github.com/google/protobuf/pull/3288

A working example can be found in: https://github.com/xfxyjwf/bazel_proto_examples/blob/master/WORKSPACE

**Comment by Stokestack** [comment]
Neither of those links works, and the "lite" option is still broken in protoc 3.7.2.

Am I missing something? Thanks.
